version: 0.0
os: linux
files:
  - source: /
    destination: airflow

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_docker.sh
      runas: root
