version: 0.0
os: linux
files:
  - source: /
    destination: home/ec2-user/app

hooks:
  BeforeInstall:
    - location: codedeploy_scripts/install_dependencies.sh
      runas: root

  ApplicationStart:
    - location: codedeploy_scripts/start_docker.sh
      runas: root
